## Author: Gabriel Vance
## Class: DSC550 - Data Mining
## Professor: Dr. Brett Werner
## Date: June 17, 2025

# Purpose: This notebook performs various tasks labeled "Exercises" for Week 3 of the class. Data must be present within the folder that this notebook is run in.
# This week focuses on Feature Selection and Dimensionality Reduction

In [31]:
import pandas as pd
import numpy as np

### Import the housing data as a data frame and ensure that the data is loaded properly.

In [32]:
test_df = pd.read_csv('train.csv')
test_df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

### Drop the "Id" column and any features that are missing more than 40% of their values.

In [33]:
# Drop the "Id" column
test_df = test_df.drop(columns=['Id'])

# Drop columns with more than 40% missing values
threshold = len(test_df) * 0.6
test_df = test_df.dropna(axis=1, thresh=threshold)

test_df.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,60,RL,65.0,8450,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,2,2008,WD,Normal,208500
1,20,RL,80.0,9600,Pave,Reg,Lvl,AllPub,FR2,Gtl,...,0,0,0,0,0,5,2007,WD,Normal,181500
2,60,RL,68.0,11250,Pave,IR1,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,9,2008,WD,Normal,223500
3,70,RL,60.0,9550,Pave,IR1,Lvl,AllPub,Corner,Gtl,...,272,0,0,0,0,2,2006,WD,Abnorml,140000
4,60,RL,84.0,14260,Pave,IR1,Lvl,AllPub,FR2,Gtl,...,0,0,0,0,0,12,2008,WD,Normal,250000

### For numerical columns, fill in any missing data with the median value.

In [34]:
# Fill missing values in numerical columns with the median
num_cols = test_df.select_dtypes(include=[np.number]).columns
test_df[num_cols] = test_df[num_cols].fillna(test_df[num_cols].median())
test_df.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,60,RL,65.0,8450,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,2,2008,WD,Normal,208500
1,20,RL,80.0,9600,Pave,Reg,Lvl,AllPub,FR2,Gtl,...,0,0,0,0,0,5,2007,WD,Normal,181500
2,60,RL,68.0,11250,Pave,IR1,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,9,2008,WD,Normal,223500
3,70,RL,60.0,9550,Pave,IR1,Lvl,AllPub,Corner,Gtl,...,272,0,0,0,0,2,2006,WD,Abnorml,140000
4,60,RL,84.0,14260,Pave,IR1,Lvl,AllPub,FR2,Gtl,...,0,0,0,0,0,12,2008,WD,Normal,250000

### For categorical columns, fill in any missing data with the most common value (mode).

In [35]:
# Fill missing values in categorical columns with the mode
cat_cols = test_df.select_dtypes(include=['object']).columns
for col in cat_cols:
    mode = test_df[col].mode()[0]
    test_df[col] = test_df[col].fillna(mode)
test_df.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,60,RL,65.0,8450,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,2,2008,WD,Normal,208500
1,20,RL,80.0,9600,Pave,Reg,Lvl,AllPub,FR2,Gtl,...,0,0,0,0,0,5,2007,WD,Normal,181500
2,60,RL,68.0,11250,Pave,IR1,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,9,2008,WD,Normal,223500
3,70,RL,60.0,9550,Pave,IR1,Lvl,AllPub,Corner,Gtl,...,272,0,0,0,0,2,2006,WD,Abnorml,140000
4,60,RL,84.0,14260,Pave,IR1,Lvl,AllPub,FR2,Gtl,...,0,0,0,0,0,12,2008,WD,Normal,250000

### Convert the categorical columns to dummy variables.

In [36]:
# Convert categorical columns to dummy variables
test_df = pd.get_dummies(test_df, columns=cat_cols, drop_first=True)
test_df.head()

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,SaleType_ConLI,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,60,65.0,8450,7,5,2003,2003,196.0,706,0,...,False,False,False,False,True,False,False,False,True,False
1,20,80.0,9600,6,8,1976,1976,0.0,978,0,...,False,False,False,False,True,False,False,False,True,False
2,60,68.0,11250,7,5,2001,2002,162.0,486,0,...,False,False,False,False,True,False,False,False,True,False
3,70,60.0,9550,7,5,1915,1970,0.0,216,0,...,False,False,False,False,True,False,False,False,False,False
4,60,84.0,14260,8,5,2000,2000,350.0,655,0,...,False,False,False,False,True,False,False,False,True,False

### Split the data into a training and test set, where the SalePrice column is the target.

In [37]:
from sklearn.model_selection import train_test_split

# Separate features and target
X = test_df.drop('SalePrice', axis=1)
y = test_df['SalePrice']

# Split into training and test sets (e.g., 80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

### Run a linear regression and report the R2-value and RMSE on the test set.

In [38]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error
import numpy as np

# Fit linear regression model
lr = LinearRegression()
lr.fit(X_train, y_train)

# Predict on test set
y_pred = lr.predict(X_test)

# Calculate R2 and RMSE
r2 = r2_score(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print(f'R2-value: {r2:.4f}')
print(f'RMSE: {rmse:.2f}')

R2-value: 0.6478
RMSE: 51973.14

### Fit and transform the training features with a PCA so that 90% of the variance is retained

In [39]:
from sklearn.decomposition import PCA

# Fit PCA to retain 90% of the variance
pca = PCA(n_components=0.90, svd_solver='full')
X_train_pca = pca.fit_transform(X_train)

print(f'Original number of features: {X_train.shape[1]}')
print(f'Number of features after PCA: {X_train_pca.shape[1]}')

Original number of features: 229
Number of features after PCA: 1

### How many features are in the PCA-transformed matrix?

In [40]:
# The number of features in the PCA-transformed matrix is:
X_train_pca.shape[1]

1

### Transform but DO NOT fit the test features with the same PCA.

In [41]:
# Transform the test features using the already-fitted PCA
X_test_pca = pca.transform(X_test)
X_test_pca.shape

(292, 1)

### Fit linear regression model on PCA-transformed data

In [42]:
# Fit linear regression model on PCA-transformed data
lr_pca = LinearRegression()
lr_pca.fit(X_train_pca, y_train)

# Predict on PCA-transformed test set
y_pred_pca = lr_pca.predict(X_test_pca)

# Calculate R2 and RMSE
r2_pca = r2_score(y_test, y_pred_pca)
rmse_pca = np.sqrt(mean_squared_error(y_test, y_pred_pca))

print(f'R2-value (PCA): {r2_pca:.4f}')
print(f'RMSE (PCA): {rmse_pca:.2f}')

R2-value (PCA): 0.0635
RMSE (PCA): 84754.58

Take your original training features  and apply a min-max scaler to them.

In [43]:
from sklearn.preprocessing import MinMaxScaler

# Apply MinMaxScaler to the original training features
scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train)

# Show the shape to confirm scaling
X_train_scaled.shape

(1168, 229)

### Find the min-max scaled features in your training set that have a variance above 0.1

In [44]:
# Calculate variance for each feature in the min-max scaled training set
variances = X_train_scaled.var(axis=0)

# Get the feature names from X_train
feature_names = X_train.columns

# Find features with variance above 0.1
high_variance_features = feature_names[variances > 0.1]
high_variance_features.tolist()

['YearRemodAdd',
 'YrSold',
 'MSZoning_RL',
 'MSZoning_RM',
 'LotShape_Reg',
 'LotConfig_Inside',
 'Neighborhood_NAmes',
 'Condition1_Norm',
 'HouseStyle_1Story',
 'HouseStyle_2Story',
 'RoofStyle_Gable',
 'RoofStyle_Hip',
 'Exterior1st_HdBoard',
 'Exterior1st_MetalSd',
 'Exterior1st_VinylSd',
 'Exterior1st_Wd Sdng',
 'Exterior2nd_HdBoard',
 'Exterior2nd_MetalSd',
 'Exterior2nd_VinylSd',
 'Exterior2nd_Wd Sdng',
 'ExterQual_Gd',
 'ExterQual_TA',
 'ExterCond_TA',
 'Foundation_CBlock',
 'Foundation_PConc',
 'BsmtQual_Gd',
 'BsmtQual_TA',
 'BsmtExposure_No',
 'BsmtFinType1_GLQ',
 'BsmtFinType1_Unf',
 'HeatingQC_Gd',
 'HeatingQC_TA',
 'KitchenQual_Gd',
 'KitchenQual_TA',
 'GarageType_Attchd',
 'GarageType_Detchd',
 'GarageFinish_RFn',
 'GarageFinish_Unf',
 'SaleType_WD',
 'SaleCondition_Normal']

### Transform but DO NOT fit the test features

In [45]:
# Transform the test features using the already-fitted MinMaxScaler
X_test_scaled = scaler.transform(X_test)
X_test_scaled.shape

(292, 229)

### Run a linear regression and report the R2-value and RMSE on the high variance data

In [46]:
# Select only the high variance features from the scaled training and test sets
X_train_highvar = X_train_scaled[:, variances > 0.1]
X_test_highvar = X_test_scaled[:, variances > 0.1]

# Fit linear regression model on high variance features
lr_highvar = LinearRegression()
lr_highvar.fit(X_train_highvar, y_train)

# Predict on test set
y_pred_highvar = lr_highvar.predict(X_test_highvar)

# Calculate R2 and RMSE
r2_highvar = r2_score(y_test, y_pred_highvar)
rmse_highvar = np.sqrt(mean_squared_error(y_test, y_pred_highvar))

print(f'R2-value (high variance): {r2_highvar:.4f}')
print(f'RMSE (high variance): {rmse_highvar:.2f}')

R2-value (high variance): 0.6481
RMSE (high variance): 51952.01