## Author: Gabriel Vance
## Class: DSC530 - Data Exporation and Analysis
## Professor: Matthew Metzger
## Date: April 18, 2025

# Purpose: This notebook performs various tasks labeled "Exercises" for Week 5 & 6 of the class. Data must be present within the folder that this notebook is run in.

In [89]:
# imports
import pandas as pd

Exercise 1.
With the earthquakes.csv file, select all the earthquakes in Japan with a magnitude of 4.9 or greater using the mb magnitude type.

In [90]:
earthquake_df = pd.read_csv("earthquakes.csv", index_col=0, parse_dates=True)
earthquake_df.head()

C:\Users\Gabe\AppData\Local\Temp\ipykernel_23244\746112779.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  earthquake_df = pd.read_csv("earthquakes.csv", index_col=0, parse_dates=True)

     magType           time                  place  tsunami parsed_place
mag
1.35      ml  1539475168010  9km NE of Aguanga, CA        0   California
1.29      ml  1539475129610  9km NE of Aguanga, CA        0   California
3.42      ml  1539475062610  8km NE of Aguanga, CA        0   California
0.44      ml  1539474978070  9km NE of Aguanga, CA        0   California
2.16      md  1539474716050  10km NW of Avenal, CA        0   California

In [91]:
# print the column names
earthquake_df.columns

Index(['magType', 'time', 'place', 'tsunami', 'parsed_place'], dtype='object')

In [92]:
# select all earthquakes with a magnitude greater than 4.9
threshold = 4.9
mb_earthquakes = earthquake_df[earthquake_df["magType"] == "mb"]
japanese_earthquakes = mb_earthquakes[mb_earthquakes["parsed_place"] == "Japan"]
earthquakes_past_threshold = japanese_earthquakes[japanese_earthquakes.index >= threshold]
earthquakes_past_threshold

    magType           time                         place  tsunami parsed_place
mag
4.9      mb  1538977532250  293km ESE of Iwo Jima, Japan        0        Japan
5.4      mb  1538697528010    37km E of Tomakomai, Japan        0        Japan
4.9      mb  1538579732490     15km ENE of Hasaki, Japan        0        Japan
4.9      mb  1538450871260    53km ESE of Hitachi, Japan        0        Japan

Exercise 2. Create bins for each full number of earthquake magnitude (for instance, the first bin is (0,1], the second is (1,2], and so on) with the ml magnitude type and count how many are in each bin.

In [93]:
ml_earthquakes = earthquake_df[earthquake_df["magType"] == "ml"]
max_magnitude = int(ml_earthquakes.index.max()) +1 # get max magnitude, use int to round up
print(f"Max magnitude: {max_magnitude}")
bins = range(0, max_magnitude , 1) # create bins from 0 to max_magnitude + 1 with a step of 1
ml_earthquakes['magnitude_bin'] = pd.cut(ml_earthquakes.index, bins=bins, right=True)
bin_counts = ml_earthquakes['magnitude_bin'].value_counts() # display counts of each bin

print(bin_counts)

Max magnitude: 6
magnitude_bin
(1, 2]    3105
(0, 1]    2207
(2, 3]     862
(3, 4]     122
(4, 5]       2
Name: count, dtype: int64

C:\Users\Gabe\AppData\Local\Temp\ipykernel_23244\3126001049.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ml_earthquakes['magnitude_bin'] = pd.cut(ml_earthquakes.index, bins=bins, right=True)

Exercise 4.
Build a crosstab with the earthquake data between the tsunami column and the magType column. Rather than showing the frequency count, show the maximum magnitude that was observed for each combination. Put the magnitude type along the columns.

In [94]:
crosstab = pd.crosstab(
    earthquake_df['tsunami'],
    earthquake_df['magType'],
    values=earthquake_df.index,
    aggfunc='max'
)

print(crosstab)

magType   mb  mb_lg    md   mh   ml  ms_20    mw  mwb  mwr  mww
tsunami
0        5.6    3.5  4.11  1.1  4.2    NaN  3.83  5.8  4.8  6.0
1        6.1    NaN   NaN  NaN  5.1    5.7  4.41  NaN  NaN  7.5

Exercise 6.
Create a pivot table of the FAANG data that compares the stocks. Put the ticker in the rows and show the averages of the OHLC and volume traded data.

In [95]:
faang_df = pd.read_csv("faang.csv", index_col=0, parse_dates=True)
faang_df.columns

C:\Users\Gabe\AppData\Local\Temp\ipykernel_23244\927585244.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  faang_df = pd.read_csv("faang.csv", index_col=0, parse_dates=True)

Index(['date', 'high', 'low', 'open', 'close', 'volume'], dtype='object')

In [96]:
# create pivot table
pivot_table = faang_df.pivot_table(
    index=faang_df.index,
    values=['open', 'high', 'low', 'close', 'volume'], # OHLC - open high low close and volume
    aggfunc='mean'
)

pivot_table

              close         high          low         open        volume
ticker
AAPL      47.263357    47.748526    46.795877    47.277859  1.360803e+08
AMZN    1641.726176  1662.839839  1619.840519  1644.072709  5.648994e+06
FB       171.510956   173.613347   169.303148   171.472948  2.765860e+07
GOOG    1113.225134  1125.777606  1101.001658  1113.554101  1.741965e+06
NFLX     319.290319   325.219322   313.187330   319.620558  1.146962e+07

Exercise 7.
Calculate the z-scores for each numeric column of Amazon’s data (ticker is AMZN) in Q4 2018 using apply().

In [97]:
faang_df.head() # print the head to see the dates, format is 2018-01-02	or YYYY-MM-DD

              date        high         low        open       close      volume
ticker
FB      2018-01-02  181.580002  177.550003  177.679993  181.419998  18151900.0
FB      2018-01-03  184.779999  181.330002  181.880005  184.669998  16886600.0
FB      2018-01-04  186.210007  184.100006  184.899994  184.330002  13880900.0
FB      2018-01-05  186.899994  184.929993  185.589996  186.850006  13574500.0
FB      2018-01-08  188.899994  186.330002  187.199997  188.279999  17994700.0

In [98]:
amzn_df = faang_df[faang_df.index == "AMZN"]
amzn_df
# note the prices are in thousands, such as 1200, 1000

,date,high,low,open,close,volume
ticker,,,,,,
AMZN,2018-01-02,1190.000000,1170.510010,1172.000000,1189.010010,2694500.0
AMZN,2018-01-03,1205.489990,1188.300049,1188.300049,1204.199951,3108800.0
AMZN,2018-01-04,1215.869995,1204.660034,1205.000000,1209.589966,3022100.0
AMZN,2018-01-05,1229.140015,1210.000000,1217.510010,1229.140015,3544700.0
AMZN,2018-01-08,1253.079956,1232.030029,1236.000000,1246.869995,4279500.0
...,...,...,...,...,...,...
AMZN,2018-12-24,1396.030029,1307.000000,1346.000000,1343.959961,7220000.0
AMZN,2018-12-26,1473.160034,1363.010010,1368.890015,1470.900024,10411800.0
AMZN,2018-12-27,1469.000000,1390.310059,1454.199951,1461.640015,9722000.0
AMZN,2018-12-28,1513.469971,1449.000000,1473.349976,1478.020020,8829000.0
AMZN,2018-12-31,1520.760010,1487.000000,1510.800049,1501.969971,6954500.0

In [99]:
# q4 2018 was oct1 to dec 31
q4_amzn = amzn_df[(amzn_df["date"] >= "2018-10-01") & (amzn_df["date"] <= "2018-12-31")]

# Z score formula is x - mean / std
q4_amzn_zcores = q4_amzn[["open", "high", "low", "close", "volume"]].apply(
    lambda x: (x - x.mean()) / x.std() # use apply and lambda 
)

# print q4 z scores
q4_amzn_zcores
# data is now standardized, so prices are down close to 0, but should they be negative?

            open      high       low     close    volume
ticker
AMZN    2.337813  2.368006  2.502113  2.385848 -1.630411
AMZN    2.190795  2.227302  2.247433  2.155037 -0.861879
AMZN    2.068570  2.058955  2.139987  2.025489 -0.920345
AMZN    1.850048  1.819474  1.781561  1.722816 -0.126582
AMZN    1.642819  1.628173  1.554416  1.584748 -0.298771
...          ...       ...       ...       ...       ...
AMZN   -2.179582 -2.159820 -2.187566 -2.226185 -0.141238
AMZN   -2.026617 -1.611714 -1.810493 -1.339674  1.123063
AMZN   -1.456521 -1.641276 -1.626703 -1.404343  0.849827
AMZN   -1.328549 -1.325261 -1.231588 -1.289951  0.496102
AMZN   -1.078283 -1.273456 -0.975763 -1.122691 -0.246405

[63 rows x 5 columns]

Exercise 10.
The European Centre for Disease Prevention and Control (ECDC) provides an open dataset on COVID-19 cases called daily number of new reported cases of COVID-19 by country worldwide. This dataset is updated daily, but we will use a snapshot that contains data through September 18, 2020. Complete the following tasks to practice the skills you've learned up to this point in the book:
Prepare the data
Read in the data in the covid19_cases.csv file.
Create a date column by parsing the dateRep column into a datetime.
Set the date column as the index.
Use the replace() method to update all occurrences of United_States_of_America and United_Kingdom to USA and UK, respectively.
Sort the index.
For the five countries with the most cases (cumulative), find the day with the largest number of cases.
Find the 7-day average change in COVID-19 cases for the last week in the data for the five countries with the most cases.
Find the first date that each country other than China had cases.
Rank the countries by cumulative cases using percentiles.

Read in the data in the covid19_cases.csv file.

In [100]:
covid_df = pd.read_csv("covid19_cases.csv")
covid_df.head()

,dateRep,day,month,year,cases,deaths,countriesAndTerritories,geoId,countryterritoryCode,popData2019,continentExp,Cumulative_number_for_14_days_of_COVID-19_cases_per_100000
0,19/09/2020,19,9,2020,47,1,Afghanistan,AF,AFG,38041757.0,Asia,1.616645
1,18/09/2020,18,9,2020,0,0,Afghanistan,AF,AFG,38041757.0,Asia,1.535155
2,17/09/2020,17,9,2020,17,0,Afghanistan,AF,AFG,38041757.0,Asia,1.653446
3,16/09/2020,16,9,2020,40,10,Afghanistan,AF,AFG,38041757.0,Asia,1.708649
4,15/09/2020,15,9,2020,99,6,Afghanistan,AF,AFG,38041757.0,Asia,1.627159

In [101]:
covid_df.columns # print column names

Index(['dateRep', 'day', 'month', 'year', 'cases', 'deaths',
       'countriesAndTerritories', 'geoId', 'countryterritoryCode',
       'popData2019', 'continentExp',
       'Cumulative_number_for_14_days_of_COVID-19_cases_per_100000'],
      dtype='object')

Create a date column by parsing the dateRep column into a datetime.

In [102]:
covid_df['date'] = pd.to_datetime(covid_df['dateRep'], format='%d/%m/%Y')
covid_df # date is now present in the dataframe

,dateRep,day,month,year,cases,deaths,countriesAndTerritories,geoId,countryterritoryCode,popData2019,continentExp,Cumulative_number_for_14_days_of_COVID-19_cases_per_100000,date
0,19/09/2020,19,9,2020,47,1,Afghanistan,AF,AFG,38041757.0,Asia,1.616645,2020-09-19
1,18/09/2020,18,9,2020,0,0,Afghanistan,AF,AFG,38041757.0,Asia,1.535155,2020-09-18
2,17/09/2020,17,9,2020,17,0,Afghanistan,AF,AFG,38041757.0,Asia,1.653446,2020-09-17
3,16/09/2020,16,9,2020,40,10,Afghanistan,AF,AFG,38041757.0,Asia,1.708649,2020-09-16
4,15/09/2020,15,9,2020,99,6,Afghanistan,AF,AFG,38041757.0,Asia,1.627159,2020-09-15
...,...,...,...,...,...,...,...,...,...,...,...,...,...
43713,25/03/2020,25,3,2020,0,0,Zimbabwe,ZW,ZWE,14645473.0,Africa,NaN,2020-03-25
43714,24/03/2020,24,3,2020,0,1,Zimbabwe,ZW,ZWE,14645473.0,Africa,NaN,2020-03-24
43715,23/03/2020,23,3,2020,0,0,Zimbabwe,ZW,ZWE,14645473.0,Africa,NaN,2020-03-23
43716,22/03/2020,22,3,2020,1,0,Zimbabwe,ZW,ZWE,14645473.0,Africa,NaN,2020-03-22
43717,21/03/2020,21,3,2020,1,0,Zimbabwe,ZW,ZWE,14645473.0,Africa,NaN,2020-03-21

Set the date column as the index.

In [103]:
covid_df = covid_df.set_index('date') # set date as index

In [104]:
covid_df.index # note that newly added date column is now the index

DatetimeIndex(['2020-09-19', '2020-09-18', '2020-09-17', '2020-09-16',
               '2020-09-15', '2020-09-14', '2020-09-13', '2020-09-12',
               '2020-09-11', '2020-09-10',
               ...
               '2020-03-30', '2020-03-29', '2020-03-28', '2020-03-27',
               '2020-03-26', '2020-03-25', '2020-03-24', '2020-03-23',
               '2020-03-22', '2020-03-21'],
              dtype='datetime64[ns]', name='date', length=43718, freq=None)

Use the replace() method to update all occurrences of United_States_of_America and United_Kingdom to USA and UK, respectively.

In [105]:
covid_df.head()

,dateRep,day,month,year,cases,deaths,countriesAndTerritories,geoId,countryterritoryCode,popData2019,continentExp,Cumulative_number_for_14_days_of_COVID-19_cases_per_100000
date,,,,,,,,,,,,
2020-09-19,19/09/2020,19,9,2020,47,1,Afghanistan,AF,AFG,38041757.0,Asia,1.616645
2020-09-18,18/09/2020,18,9,2020,0,0,Afghanistan,AF,AFG,38041757.0,Asia,1.535155
2020-09-17,17/09/2020,17,9,2020,17,0,Afghanistan,AF,AFG,38041757.0,Asia,1.653446
2020-09-16,16/09/2020,16,9,2020,40,10,Afghanistan,AF,AFG,38041757.0,Asia,1.708649
2020-09-15,15/09/2020,15,9,2020,99,6,Afghanistan,AF,AFG,38041757.0,Asia,1.627159

In [106]:
covid_df['countriesAndTerritories'].unique() # just to see the countries

array(['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola',
       'Anguilla', 'Antigua_and_Barbuda', 'Argentina', 'Armenia', 'Aruba',
       'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain',
       'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin',
       'Bermuda', 'Bhutan', 'Bolivia',
       'Bonaire, Saint Eustatius and Saba', 'Bosnia_and_Herzegovina',
       'Botswana', 'Brazil', 'British_Virgin_Islands',
       'Brunei_Darussalam', 'Bulgaria', 'Burkina_Faso', 'Burundi',
       'Cambodia', 'Cameroon', 'Canada', 'Cape_Verde',
       'Cases_on_an_international_conveyance_Japan', 'Cayman_Islands',
       'Central_African_Republic', 'Chad', 'Chile', 'China', 'Colombia',
       'Comoros', 'Congo', 'Costa_Rica', 'Cote_dIvoire', 'Croatia',
       'Cuba', 'Curaçao', 'Cyprus', 'Czechia',
       'Democratic_Republic_of_the_Congo', 'Denmark', 'Djibouti',
       'Dominica', 'Dominican_Republic', 'Ecuador', 'Egypt',
       'El_Salvador', 'Equatorial_Guinea', 'Eritrea', 'Estonia',
       'Eswatini', 'Ethiopia', 'Falkland_Islands_(Malvinas)',
       'Faroe_Islands', 'Fiji', 'Finland', 'France', 'French_Polynesia',
       'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana', 'Gibraltar',
       'Greece', 'Greenland', 'Grenada', 'Guam', 'Guatemala', 'Guernsey',
       'Guinea', 'Guinea_Bissau', 'Guyana', 'Haiti', 'Holy_See',
       'Honduras', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran',
       'Iraq', 'Ireland', 'Isle_of_Man', 'Israel', 'Italy', 'Jamaica',
       'Japan', 'Jersey', 'Jordan', 'Kazakhstan', 'Kenya', 'Kosovo',
       'Kuwait', 'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon', 'Lesotho',
       'Liberia', 'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg',
       'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta',
       'Mauritania', 'Mauritius', 'Mexico', 'Moldova', 'Monaco',
       'Mongolia', 'Montenegro', 'Montserrat', 'Morocco', 'Mozambique',
       'Myanmar', 'Namibia', 'Nepal', 'Netherlands', 'New_Caledonia',
       'New_Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'North_Macedonia',
       'Northern_Mariana_Islands', 'Norway', 'Oman', 'Pakistan',
       'Palestine', 'Panama', 'Papua_New_Guinea', 'Paraguay', 'Peru',
       'Philippines', 'Poland', 'Portugal', 'Puerto_Rico', 'Qatar',
       'Romania', 'Russia', 'Rwanda', 'Saint_Kitts_and_Nevis',
       'Saint_Lucia', 'Saint_Vincent_and_the_Grenadines', 'San_Marino',
       'Sao_Tome_and_Principe', 'Saudi_Arabia', 'Senegal', 'Serbia',
       'Seychelles', 'Sierra_Leone', 'Singapore', 'Sint_Maarten',
       'Slovakia', 'Slovenia', 'Somalia', 'South_Africa', 'South_Korea',
       'South_Sudan', 'Spain', 'Sri_Lanka', 'Sudan', 'Suriname', 'Sweden',
       'Switzerland', 'Syria', 'Taiwan', 'Tajikistan', 'Thailand',
       'Timor_Leste', 'Togo', 'Trinidad_and_Tobago', 'Tunisia', 'Turkey',
       'Turks_and_Caicos_islands', 'Uganda', 'Ukraine',
       'United_Arab_Emirates', 'United_Kingdom',
       'United_Republic_of_Tanzania', 'United_States_of_America',
       'United_States_Virgin_Islands', 'Uruguay', 'Uzbekistan',
       'Venezuela', 'Vietnam', 'Western_Sahara', 'Yemen', 'Zambia',
       'Zimbabwe'], dtype=object)

In [107]:
covid_df['countriesAndTerritories'] = covid_df['countriesAndTerritories'].replace(
    {'United_States_of_America': 'USA', 'United_Kingdom': 'UK'}
)
covid_df['countriesAndTerritories'].unique() # we can print again, note that the names changed

array(['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola',
       'Anguilla', 'Antigua_and_Barbuda', 'Argentina', 'Armenia', 'Aruba',
       'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain',
       'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin',
       'Bermuda', 'Bhutan', 'Bolivia',
       'Bonaire, Saint Eustatius and Saba', 'Bosnia_and_Herzegovina',
       'Botswana', 'Brazil', 'British_Virgin_Islands',
       'Brunei_Darussalam', 'Bulgaria', 'Burkina_Faso', 'Burundi',
       'Cambodia', 'Cameroon', 'Canada', 'Cape_Verde',
       'Cases_on_an_international_conveyance_Japan', 'Cayman_Islands',
       'Central_African_Republic', 'Chad', 'Chile', 'China', 'Colombia',
       'Comoros', 'Congo', 'Costa_Rica', 'Cote_dIvoire', 'Croatia',
       'Cuba', 'Curaçao', 'Cyprus', 'Czechia',
       'Democratic_Republic_of_the_Congo', 'Denmark', 'Djibouti',
       'Dominica', 'Dominican_Republic', 'Ecuador', 'Egypt',
       'El_Salvador', 'Equatorial_Guinea', 'Eritrea', 'Estonia',
       'Eswatini', 'Ethiopia', 'Falkland_Islands_(Malvinas)',
       'Faroe_Islands', 'Fiji', 'Finland', 'France', 'French_Polynesia',
       'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana', 'Gibraltar',
       'Greece', 'Greenland', 'Grenada', 'Guam', 'Guatemala', 'Guernsey',
       'Guinea', 'Guinea_Bissau', 'Guyana', 'Haiti', 'Holy_See',
       'Honduras', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran',
       'Iraq', 'Ireland', 'Isle_of_Man', 'Israel', 'Italy', 'Jamaica',
       'Japan', 'Jersey', 'Jordan', 'Kazakhstan', 'Kenya', 'Kosovo',
       'Kuwait', 'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon', 'Lesotho',
       'Liberia', 'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg',
       'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta',
       'Mauritania', 'Mauritius', 'Mexico', 'Moldova', 'Monaco',
       'Mongolia', 'Montenegro', 'Montserrat', 'Morocco', 'Mozambique',
       'Myanmar', 'Namibia', 'Nepal', 'Netherlands', 'New_Caledonia',
       'New_Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'North_Macedonia',
       'Northern_Mariana_Islands', 'Norway', 'Oman', 'Pakistan',
       'Palestine', 'Panama', 'Papua_New_Guinea', 'Paraguay', 'Peru',
       'Philippines', 'Poland', 'Portugal', 'Puerto_Rico', 'Qatar',
       'Romania', 'Russia', 'Rwanda', 'Saint_Kitts_and_Nevis',
       'Saint_Lucia', 'Saint_Vincent_and_the_Grenadines', 'San_Marino',
       'Sao_Tome_and_Principe', 'Saudi_Arabia', 'Senegal', 'Serbia',
       'Seychelles', 'Sierra_Leone', 'Singapore', 'Sint_Maarten',
       'Slovakia', 'Slovenia', 'Somalia', 'South_Africa', 'South_Korea',
       'South_Sudan', 'Spain', 'Sri_Lanka', 'Sudan', 'Suriname', 'Sweden',
       'Switzerland', 'Syria', 'Taiwan', 'Tajikistan', 'Thailand',
       'Timor_Leste', 'Togo', 'Trinidad_and_Tobago', 'Tunisia', 'Turkey',
       'Turks_and_Caicos_islands', 'Uganda', 'Ukraine',
       'United_Arab_Emirates', 'UK', 'United_Republic_of_Tanzania', 'USA',
       'United_States_Virgin_Islands', 'Uruguay', 'Uzbekistan',
       'Venezuela', 'Vietnam', 'Western_Sahara', 'Yemen', 'Zambia',
       'Zimbabwe'], dtype=object)

Sort the index.

In [108]:
covid_df = covid_df.sort_index(ascending=True) # sort but have to make it ascending to earlier dates are first
covid_df

,dateRep,day,month,year,cases,deaths,countriesAndTerritories,geoId,countryterritoryCode,popData2019,continentExp,Cumulative_number_for_14_days_of_COVID-19_cases_per_100000
date,,,,,,,,,,,,
2019-12-31,31/12/2019,31,12,2019,0,0,Belgium,BE,BEL,11455519.0,Europe,NaN
2019-12-31,31/12/2019,31,12,2019,0,0,Mexico,MX,MEX,127575529.0,America,NaN
2019-12-31,31/12/2019,31,12,2019,0,0,Ecuador,EC,ECU,17373657.0,America,NaN
2019-12-31,31/12/2019,31,12,2019,0,0,Russia,RU,RUS,145872260.0,Europe,NaN
2019-12-31,31/12/2019,31,12,2019,0,0,Netherlands,NL,NLD,17282163.0,Europe,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
2020-09-19,19/09/2020,19,9,2020,77,0,Guinea,GN,GIN,12771246.0,Africa,5.105218
2020-09-19,19/09/2020,19,9,2020,1771,62,Turkey,TR,TUR,82003882.0,Asia,28.358414
2020-09-19,19/09/2020,19,9,2020,28,0,Guinea_Bissau,GW,GNB,1920917.0,Africa,3.019391
2020-09-19,19/09/2020,19,9,2020,0,0,Tunisia,TN,TUN,11694721.0,Africa,35.708419
2020-09-19,19/09/2020,19,9,2020,47,1,Afghanistan,AF,AFG,38041757.0,Asia,1.616645

For the five countries with the most cases (cumulative), find the day with the largest number of cases.
Find the 7-day average change in COVID-19 cases for the last week in the data for the five countries with the most cases.

In [109]:
total_cases = covid_df.groupby('countriesAndTerritories')['cases'].sum() # this gets the sum of all cases by country
top_countries = total_cases.sort_values(ascending=False).head(5).index # top 5
country_names = top_countries.to_list()
# top countries are USA, India, Brazil, Russia, Peru
country_names

['USA', 'India', 'Brazil', 'Russia', 'Peru']

In [110]:
def parse_country_data(country):
    country_df = covid_df[covid_df['countriesAndTerritories'] == country] # filter for country
    sorted_by_cases = country_df.sort_values(by='cases',ascending=True) # sort by cases, ascending
    top_date = sorted_by_cases.iloc[-1] # get the date of the last case
    top_date_value = top_date.name
    # average change - the mean difference between 7 consecutive days
    last_week = country_df.tail(7)
    last_week['average_change'] = last_week['cases'].diff()
    average = last_week['average_change'].mean()
    print(f"{country}'s top date for COVID-19 cases is {top_date_value}. The average change in the last week is {average:.2f} cases.")

for country in country_names:
    parse_country_data(country)

USA's top date for COVID-19 cases is 2020-07-25 00:00:00. The average change in the last week is 1564.83 cases.
India's top date for COVID-19 cases is 2020-09-17 00:00:00. The average change in the last week is -172.50 cases.
Brazil's top date for COVID-19 cases is 2020-07-30 00:00:00. The average change in the last week is 1045.67 cases.
Russia's top date for COVID-19 cases is 2020-07-18 00:00:00. The average change in the last week is 69.50 cases.
Peru's top date for COVID-19 cases is 2020-08-17 00:00:00. The average change in the last week is 25.33 cases.

C:\Users\Gabe\AppData\Local\Temp\ipykernel_23244\2492448502.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_week['average_change'] = last_week['cases'].diff()
C:\Users\Gabe\AppData\Local\Temp\ipykernel_23244\2492448502.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_week['average_change'] = last_week['cases'].diff()
C:\Users\Gabe\AppData\Local\Temp\ipykernel_23244\2492448502.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_week['average_change'] = last_week['cases'].diff()
C:\Users\Gabe\AppData\Local\Temp\ipykernel_23244\2492448502.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_week['average_change'] = last_week['cases'].diff()
C:\Users\Gabe\AppData\Local\Temp\ipykernel_23244\2492448502.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_week['average_change'] = last_week['cases'].diff()

Find the first date that each country other than China had cases.

In [111]:
all_countries = total_cases.sort_values(ascending=False).index.to_list()
"China" in all_countries

True

In [112]:
all_countries = total_cases.sort_values(ascending=False).index.to_list()
all_countries.remove("China")
"China" in all_countries # check if China is removed

False

In [113]:
all_countries

['USA',
 'India',
 'Brazil',
 'Russia',
 'Peru',
 'Colombia',
 'Mexico',
 'South_Africa',
 'Spain',
 'Argentina',
 'Chile',
 'France',
 'Iran',
 'UK',
 'Bangladesh',
 'Saudi_Arabia',
 'Iraq',
 'Pakistan',
 'Turkey',
 'Italy',
 'Philippines',
 'Germany',
 'Indonesia',
 'Israel',
 'Ukraine',
 'Canada',
 'Kazakhstan',
 'Bolivia',
 'Ecuador',
 'Qatar',
 'Romania',
 'Dominican_Republic',
 'Panama',
 'Egypt',
 'Belgium',
 'Kuwait',
 'Morocco',
 'Oman',
 'Netherlands',
 'Sweden',
 'Guatemala',
 'United_Arab_Emirates',
 'Japan',
 'Poland',
 'Belarus',
 'Honduras',
 'Ethiopia',
 'Portugal',
 'Venezuela',
 'Bahrain',
 'Costa_Rica',
 'Nepal',
 'Singapore',
 'Nigeria',
 'Uzbekistan',
 'Algeria',
 'Switzerland',
 'Armenia',
 'Czechia',
 'Ghana',
 'Moldova',
 'Kyrgyzstan',
 'Palestine',
 'Puerto_Rico',
 'Afghanistan',
 'Azerbaijan',
 'Austria',
 'Kenya',
 'Serbia',
 'Ireland',
 'Paraguay',
 'Lebanon',
 'El_Salvador',
 'Australia',
 'Libya',
 'Bosnia_and_Herzegovina',
 'South_Korea',
 'Denmark',
 'Cameroon',
 'Cote_dIvoire',
 'Bulgaria',
 'Hungary',
 'North_Macedonia',
 'Madagascar',
 'Kosovo',
 'Greece',
 'Senegal',
 'Croatia',
 'Zambia',
 'Sudan',
 'Norway',
 'Albania',
 'Democratic_Republic_of_the_Congo',
 'Guinea',
 'Namibia',
 'Malaysia',
 'Maldives',
 'Tajikistan',
 'Finland',
 'Gabon',
 'Haiti',
 'Tunisia',
 'Luxembourg',
 'Montenegro',
 'Zimbabwe',
 'Mauritania',
 'Mozambique',
 'Slovakia',
 'Malawi',
 'Uganda',
 'Djibouti',
 'Eswatini',
 'Cape_Verde',
 'Cuba',
 'Equatorial_Guinea',
 'Congo',
 'Nicaragua',
 'Central_African_Republic',
 'Suriname',
 'Rwanda',
 'Myanmar',
 'Jamaica',
 'Jordan',
 'Slovenia',
 'Angola',
 'Syria',
 'Trinidad_and_Tobago',
 'Lithuania',
 'Thailand',
 'Gambia',
 'Aruba',
 'Somalia',
 'Georgia',
 'Sri_Lanka',
 'Bahamas',
 'Mali',
 'Estonia',
 'Malta',
 'South_Sudan',
 'Botswana',
 'Guinea_Bissau',
 'Benin',
 'Iceland',
 'Sierra_Leone',
 'Guyana',
 'Guam',
 'Yemen',
 'Uruguay',
 'Burkina_Faso',
 'Togo',
 'Belize',
 'Cyprus',
 'Andorra',
 'Latvia',
 'New_Zealand',
 'Liberia',
 'Lesotho',
 'United_States_Virgin_Islands',
 'French_Polynesia',
 'Niger',
 'Chad',
 'Vietnam',
 'Sao_Tome_and_Principe',
 'Western_Sahara',
 'San_Marino',
 'Cases_on_an_international_conveyance_Japan',
 'Turks_and_Caicos_islands',
 'Sint_Maarten',
 'Papua_New_Guinea',
 'United_Republic_of_Tanzania',
 'Taiwan',
 'Burundi',
 'Comoros',
 'Faroe_Islands',
 'Jersey',
 'Mauritius',
 'Eritrea',
 'Gibraltar',
 'Isle_of_Man',
 'Mongolia',
 'Cambodia',
 'Bhutan',
 'Guernsey',
 'Curaçao',
 'Cayman_Islands',
 'Monaco',
 'Barbados',
 'Bermuda',
 'Brunei_Darussalam',
 'Seychelles',
 'Liechtenstein',
 'Antigua_and_Barbuda',
 'British_Virgin_Islands',
 'Saint_Vincent_and_the_Grenadines',
 'Northern_Mariana_Islands',
 'Bonaire, Saint Eustatius and Saba',
 'Fiji',
 'Saint_Lucia',
 'Timor_Leste',
 'New_Caledonia',
 'Grenada',
 'Dominica',
 'Laos',
 'Saint_Kitts_and_Nevis',
 'Greenland',
 'Montserrat',
 'Falkland_Islands_(Malvinas)',
 'Holy_See',
 'Anguilla']

In [114]:
def determine_first_date_of_covid_cases(country):
    country_df = covid_df[(covid_df['countriesAndTerritories'] == country) & (covid_df['cases'] > 0)] # filter for country AND cases greater than 0
    sorted_by_cases = country_df.sort_values(by='cases',ascending=True) # sort by cases, ascending
    first_date = sorted_by_cases.iloc[0] # get the date of the first case
    first_date_value = first_date.name
    print(f"{country}'s first date for COVID-19 cases is {first_date_value}.")
    
for country in all_countries:
    determine_first_date_of_covid_cases(country)

USA's first date for COVID-19 cases is 2020-01-21 00:00:00.
India's first date for COVID-19 cases is 2020-01-30 00:00:00.
Brazil's first date for COVID-19 cases is 2020-02-26 00:00:00.
Russia's first date for COVID-19 cases is 2020-03-03 00:00:00.
Peru's first date for COVID-19 cases is 2020-03-07 00:00:00.
Colombia's first date for COVID-19 cases is 2020-03-07 00:00:00.
Mexico's first date for COVID-19 cases is 2020-03-02 00:00:00.
South_Africa's first date for COVID-19 cases is 2020-03-06 00:00:00.
Spain's first date for COVID-19 cases is 2020-02-01 00:00:00.
Argentina's first date for COVID-19 cases is 2020-03-04 00:00:00.
Chile's first date for COVID-19 cases is 2020-03-04 00:00:00.
France's first date for COVID-19 cases is 2020-01-29 00:00:00.
Iran's first date for COVID-19 cases is 2020-02-20 00:00:00.
UK's first date for COVID-19 cases is 2020-02-05 00:00:00.
Bangladesh's first date for COVID-19 cases is 2020-03-30 00:00:00.
Saudi_Arabia's first date for COVID-19 cases is 2020-03-03 00:00:00.
Iraq's first date for COVID-19 cases is 2020-02-25 00:00:00.
Pakistan's first date for COVID-19 cases is 2020-03-04 00:00:00.
Turkey's first date for COVID-19 cases is 2020-03-12 00:00:00.
Italy's first date for COVID-19 cases is 2020-01-31 00:00:00.
Philippines's first date for COVID-19 cases is 2020-01-30 00:00:00.
Germany's first date for COVID-19 cases is 2020-01-28 00:00:00.
Indonesia's first date for COVID-19 cases is 2020-03-02 00:00:00.
Israel's first date for COVID-19 cases is 2020-02-22 00:00:00.
Ukraine's first date for COVID-19 cases is 2020-03-04 00:00:00.
Canada's first date for COVID-19 cases is 2020-01-26 00:00:00.
Kazakhstan's first date for COVID-19 cases is 2020-03-17 00:00:00.
Bolivia's first date for COVID-19 cases is 2020-03-24 00:00:00.
Ecuador's first date for COVID-19 cases is 2020-03-01 00:00:00.
Qatar's first date for COVID-19 cases is 2020-03-01 00:00:00.
Romania's first date for COVID-19 cases is 2020-02-27 00:00:00.
Dominican_Republic's first date for COVID-19 cases is 2020-03-02 00:00:00.
Panama's first date for COVID-19 cases is 2020-03-10 00:00:00.
Egypt's first date for COVID-19 cases is 2020-02-15 00:00:00.
Belgium's first date for COVID-19 cases is 2020-02-04 00:00:00.
Kuwait's first date for COVID-19 cases is 2020-03-24 00:00:00.
Morocco's first date for COVID-19 cases is 2020-03-03 00:00:00.
Oman's first date for COVID-19 cases is 2020-03-03 00:00:00.
Netherlands's first date for COVID-19 cases is 2020-02-28 00:00:00.
Sweden's first date for COVID-19 cases is 2020-02-01 00:00:00.
Guatemala's first date for COVID-19 cases is 2020-03-15 00:00:00.
United_Arab_Emirates's first date for COVID-19 cases is 2020-01-27 00:00:00.
Japan's first date for COVID-19 cases is 2020-01-15 00:00:00.
Poland's first date for COVID-19 cases is 2020-03-04 00:00:00.
Belarus's first date for COVID-19 cases is 2020-02-28 00:00:00.
Honduras's first date for COVID-19 cases is 2020-03-14 00:00:00.
Ethiopia's first date for COVID-19 cases is 2020-03-14 00:00:00.
Portugal's first date for COVID-19 cases is 2020-03-05 00:00:00.
Venezuela's first date for COVID-19 cases is 2020-04-09 00:00:00.
Bahrain's first date for COVID-19 cases is 2020-02-24 00:00:00.
Costa_Rica's first date for COVID-19 cases is 2020-03-07 00:00:00.
Nepal's first date for COVID-19 cases is 2020-01-25 00:00:00.
Singapore's first date for COVID-19 cases is 2020-02-22 00:00:00.
Nigeria's first date for COVID-19 cases is 2020-02-28 00:00:00.
Uzbekistan's first date for COVID-19 cases is 2020-03-17 00:00:00.
Algeria's first date for COVID-19 cases is 2020-02-26 00:00:00.
Switzerland's first date for COVID-19 cases is 2020-02-26 00:00:00.
Armenia's first date for COVID-19 cases is 2020-03-01 00:00:00.
Czechia's first date for COVID-19 cases is 2020-03-03 00:00:00.
Ghana's first date for COVID-19 cases is 2020-03-19 00:00:00.
Moldova's first date for COVID-19 cases is 2020-03-08 00:00:00.
Kyrgyzstan's first date for COVID-19 cases is 2020-03-24 00:00:00.
Palestine's first date for COVID-19 cases is 2020-04-24 00:00:00.
Puerto_Rico's first date for COVID-19 cases is 2020-09-10 00:00:00.
Afghanistan's first date for COVID-19 cases is 2020-02-25 00:00:00.
Azerbaijan's first date for COVID-19 cases is 2020-02-29 00:00:00.
Austria's first date for COVID-19 cases is 2020-02-26 00:00:00.
Kenya's first date for COVID-19 cases is 2020-03-14 00:00:00.
Serbia's first date for COVID-19 cases is 2020-03-07 00:00:00.
Ireland's first date for COVID-19 cases is 2020-03-01 00:00:00.
Paraguay's first date for COVID-19 cases is 2020-03-08 00:00:00.
Lebanon's first date for COVID-19 cases is 2020-02-22 00:00:00.
El_Salvador's first date for COVID-19 cases is 2020-03-19 00:00:00.
Australia's first date for COVID-19 cases is 2020-01-25 00:00:00.
Libya's first date for COVID-19 cases is 2020-03-25 00:00:00.
Bosnia_and_Herzegovina's first date for COVID-19 cases is 2020-03-12 00:00:00.
South_Korea's first date for COVID-19 cases is 2020-01-20 00:00:00.
Denmark's first date for COVID-19 cases is 2020-02-27 00:00:00.
Cameroon's first date for COVID-19 cases is 2020-03-07 00:00:00.
Cote_dIvoire's first date for COVID-19 cases is 2020-03-12 00:00:00.
Bulgaria's first date for COVID-19 cases is 2020-03-08 00:00:00.
Hungary's first date for COVID-19 cases is 2020-03-09 00:00:00.
North_Macedonia's first date for COVID-19 cases is 2020-02-27 00:00:00.
Madagascar's first date for COVID-19 cases is 2020-03-28 00:00:00.
Kosovo's first date for COVID-19 cases is 2020-05-22 00:00:00.
Greece's first date for COVID-19 cases is 2020-02-27 00:00:00.
Senegal's first date for COVID-19 cases is 2020-03-03 00:00:00.
Croatia's first date for COVID-19 cases is 2020-02-26 00:00:00.
Zambia's first date for COVID-19 cases is 2020-06-15 00:00:00.
Sudan's first date for COVID-19 cases is 2020-03-14 00:00:00.
Norway's first date for COVID-19 cases is 2020-02-27 00:00:00.
Albania's first date for COVID-19 cases is 2020-05-20 00:00:00.
Democratic_Republic_of_the_Congo's first date for COVID-19 cases is 2020-03-11 00:00:00.
Guinea's first date for COVID-19 cases is 2020-03-14 00:00:00.
Namibia's first date for COVID-19 cases is 2020-06-02 00:00:00.
Malaysia's first date for COVID-19 cases is 2020-02-14 00:00:00.
Maldives's first date for COVID-19 cases is 2020-03-30 00:00:00.
Tajikistan's first date for COVID-19 cases is 2020-05-01 00:00:00.
Finland's first date for COVID-19 cases is 2020-01-30 00:00:00.
Gabon's first date for COVID-19 cases is 2020-03-13 00:00:00.
Haiti's first date for COVID-19 cases is 2020-04-16 00:00:00.
Tunisia's first date for COVID-19 cases is 2020-03-03 00:00:00.
Luxembourg's first date for COVID-19 cases is 2020-03-01 00:00:00.
Montenegro's first date for COVID-19 cases is 2020-06-16 00:00:00.
Zimbabwe's first date for COVID-19 cases is 2020-03-21 00:00:00.
Mauritania's first date for COVID-19 cases is 2020-03-15 00:00:00.
Mozambique's first date for COVID-19 cases is 2020-03-23 00:00:00.
Slovakia's first date for COVID-19 cases is 2020-03-07 00:00:00.
Malawi's first date for COVID-19 cases is 2020-05-03 00:00:00.
Uganda's first date for COVID-19 cases is 2020-03-22 00:00:00.
Djibouti's first date for COVID-19 cases is 2020-03-19 00:00:00.
Eswatini's first date for COVID-19 cases is 2020-03-15 00:00:00.
Cape_Verde's first date for COVID-19 cases is 2020-03-22 00:00:00.
Cuba's first date for COVID-19 cases is 2020-03-14 00:00:00.
Equatorial_Guinea's first date for COVID-19 cases is 2020-03-15 00:00:00.
Congo's first date for COVID-19 cases is 2020-03-16 00:00:00.
Nicaragua's first date for COVID-19 cases is 2020-03-19 00:00:00.
Central_African_Republic's first date for COVID-19 cases is 2020-03-16 00:00:00.
Suriname's first date for COVID-19 cases is 2020-03-15 00:00:00.
Rwanda's first date for COVID-19 cases is 2020-03-15 00:00:00.
Myanmar's first date for COVID-19 cases is 2020-06-25 00:00:00.
Jamaica's first date for COVID-19 cases is 2020-07-30 00:00:00.
Jordan's first date for COVID-19 cases is 2020-03-03 00:00:00.
Slovenia's first date for COVID-19 cases is 2020-03-05 00:00:00.
Angola's first date for COVID-19 cases is 2020-06-09 00:00:00.
Syria's first date for COVID-19 cases is 2020-03-23 00:00:00.
Trinidad_and_Tobago's first date for COVID-19 cases is 2020-03-13 00:00:00.
Lithuania's first date for COVID-19 cases is 2020-02-28 00:00:00.
Thailand's first date for COVID-19 cases is 2020-01-13 00:00:00.
Gambia's first date for COVID-19 cases is 2020-03-18 00:00:00.
Aruba's first date for COVID-19 cases is 2020-04-16 00:00:00.
Somalia's first date for COVID-19 cases is 2020-03-17 00:00:00.
Georgia's first date for COVID-19 cases is 2020-02-27 00:00:00.
Sri_Lanka's first date for COVID-19 cases is 2020-01-28 00:00:00.
Bahamas's first date for COVID-19 cases is 2020-03-16 00:00:00.
Mali's first date for COVID-19 cases is 2020-08-20 00:00:00.
Estonia's first date for COVID-19 cases is 2020-02-28 00:00:00.
Malta's first date for COVID-19 cases is 2020-03-07 00:00:00.
South_Sudan's first date for COVID-19 cases is 2020-04-06 00:00:00.
Botswana's first date for COVID-19 cases is 2020-05-18 00:00:00.
Guinea_Bissau's first date for COVID-19 cases is 2020-04-27 00:00:00.
Benin's first date for COVID-19 cases is 2020-03-17 00:00:00.
Iceland's first date for COVID-19 cases is 2020-02-29 00:00:00.
Sierra_Leone's first date for COVID-19 cases is 2020-04-01 00:00:00.
Guyana's first date for COVID-19 cases is 2020-03-13 00:00:00.
Guam's first date for COVID-19 cases is 2020-06-27 00:00:00.
Yemen's first date for COVID-19 cases is 2020-04-10 00:00:00.
Uruguay's first date for COVID-19 cases is 2020-06-19 00:00:00.
Burkina_Faso's first date for COVID-19 cases is 2020-06-17 00:00:00.
Togo's first date for COVID-19 cases is 2020-03-07 00:00:00.
Belize's first date for COVID-19 cases is 2020-03-24 00:00:00.
Cyprus's first date for COVID-19 cases is 2020-06-25 00:00:00.
Andorra's first date for COVID-19 cases is 2020-03-03 00:00:00.
Latvia's first date for COVID-19 cases is 2020-03-03 00:00:00.
New_Zealand's first date for COVID-19 cases is 2020-02-28 00:00:00.
Liberia's first date for COVID-19 cases is 2020-03-17 00:00:00.
Lesotho's first date for COVID-19 cases is 2020-05-15 00:00:00.
United_States_Virgin_Islands's first date for COVID-19 cases is 2020-06-26 00:00:00.
French_Polynesia's first date for COVID-19 cases is 2020-04-06 00:00:00.
Niger's first date for COVID-19 cases is 2020-03-21 00:00:00.
Chad's first date for COVID-19 cases is 2020-03-20 00:00:00.
Vietnam's first date for COVID-19 cases is 2020-06-29 00:00:00.
Sao_Tome_and_Principe's first date for COVID-19 cases is 2020-06-28 00:00:00.
Western_Sahara's first date for COVID-19 cases is 2020-06-20 00:00:00.
San_Marino's first date for COVID-19 cases is 2020-02-28 00:00:00.
Cases_on_an_international_conveyance_Japan's first date for COVID-19 cases is 2020-02-08 00:00:00.
Turks_and_Caicos_islands's first date for COVID-19 cases is 2020-03-25 00:00:00.
Sint_Maarten's first date for COVID-19 cases is 2020-03-03 00:00:00.
Papua_New_Guinea's first date for COVID-19 cases is 2020-03-21 00:00:00.
United_Republic_of_Tanzania's first date for COVID-19 cases is 2020-03-17 00:00:00.
Taiwan's first date for COVID-19 cases is 2020-01-21 00:00:00.
Burundi's first date for COVID-19 cases is 2020-09-18 00:00:00.
Comoros's first date for COVID-19 cases is 2020-05-02 00:00:00.
Faroe_Islands's first date for COVID-19 cases is 2020-03-06 00:00:00.
Jersey's first date for COVID-19 cases is 2020-05-28 00:00:00.
Mauritius's first date for COVID-19 cases is 2020-09-19 00:00:00.
Eritrea's first date for COVID-19 cases is 2020-03-22 00:00:00.
Gibraltar's first date for COVID-19 cases is 2020-07-07 00:00:00.
Isle_of_Man's first date for COVID-19 cases is 2020-03-21 00:00:00.
Mongolia's first date for COVID-19 cases is 2020-03-10 00:00:00.
Cambodia's first date for COVID-19 cases is 2020-01-28 00:00:00.
Bhutan's first date for COVID-19 cases is 2020-03-06 00:00:00.
Guernsey's first date for COVID-19 cases is 2020-03-20 00:00:00.
Curaçao's first date for COVID-19 cases is 2020-03-13 00:00:00.
Cayman_Islands's first date for COVID-19 cases is 2020-03-20 00:00:00.
Monaco's first date for COVID-19 cases is 2020-02-29 00:00:00.
Barbados's first date for COVID-19 cases is 2020-03-18 00:00:00.
Bermuda's first date for COVID-19 cases is 2020-09-17 00:00:00.
Brunei_Darussalam's first date for COVID-19 cases is 2020-03-10 00:00:00.
Seychelles's first date for COVID-19 cases is 2020-09-18 00:00:00.
Liechtenstein's first date for COVID-19 cases is 2020-03-05 00:00:00.
Antigua_and_Barbuda's first date for COVID-19 cases is 2020-03-15 00:00:00.
British_Virgin_Islands's first date for COVID-19 cases is 2020-08-21 00:00:00.
Saint_Vincent_and_the_Grenadines's first date for COVID-19 cases is 2020-03-13 00:00:00.
Northern_Mariana_Islands's first date for COVID-19 cases is 2020-09-18 00:00:00.
Bonaire, Saint Eustatius and Saba's first date for COVID-19 cases is 2020-08-28 00:00:00.
Fiji's first date for COVID-19 cases is 2020-03-20 00:00:00.
Saint_Lucia's first date for COVID-19 cases is 2020-03-26 00:00:00.
Timor_Leste's first date for COVID-19 cases is 2020-03-22 00:00:00.
New_Caledonia's first date for COVID-19 cases is 2020-03-23 00:00:00.
Grenada's first date for COVID-19 cases is 2020-03-23 00:00:00.
Dominica's first date for COVID-19 cases is 2020-03-23 00:00:00.
Laos's first date for COVID-19 cases is 2020-04-02 00:00:00.
Saint_Kitts_and_Nevis's first date for COVID-19 cases is 2020-04-01 00:00:00.
Greenland's first date for COVID-19 cases is 2020-03-26 00:00:00.
Montserrat's first date for COVID-19 cases is 2020-03-21 00:00:00.
Falkland_Islands_(Malvinas)'s first date for COVID-19 cases is 2020-04-04 00:00:00.
Holy_See's first date for COVID-19 cases is 2020-03-07 00:00:00.
Anguilla's first date for COVID-19 cases is 2020-04-03 00:00:00.

Rank the countries by cumulative cases using percentiles.

In [115]:
# We already did something similar to this in total_cases
cumulative_countries = total_cases.sort_values(ascending=False)
cumulative_countries

countriesAndTerritories
USA                            6724667
India                          5308014
Brazil                         4495183
Russia                         1091186
Peru                            756412
                                ...
Greenland                           14
Montserrat                          13
Falkland_Islands_(Malvinas)         13
Holy_See                            12
Anguilla                             3
Name: cases, Length: 210, dtype: int64

In [116]:
# rank countries, use percentile rank
cumulative_percentiles = cumulative_countries.rank(pct=True)
cumulative_percentiles

countriesAndTerritories
USA                            1.000000
India                          0.995238
Brazil                         0.990476
Russia                         0.985714
Peru                           0.980952
                                 ...
Greenland                      0.023810
Montserrat                     0.016667
Falkland_Islands_(Malvinas)    0.016667
Holy_See                       0.009524
Anguilla                       0.004762
Name: cases, Length: 210, dtype: float64